set nocompatible
filetype off

source ~/.dotfiles/vim/bundles

source ~/.dotfiles/vim/keymaps

source ~/.dotfiles/vim/bundle/BufOnly.vim

set noswapfile
set smarttab smartindent
set number
set laststatus=2

set tabstop=4
set shiftwidth=4
set expandtab

autocmd FileType python setlocal et ts=4 sw=4
autocmd FileType html setlocal et ts=2 sw=2
autocmd FileType coffee setlocal et ts=2 sw=2

let g:ycm_autoclose_preview_window_after_completion = 1

nmap <leader>w :silent !google-chrome %<CR>

syntax on

match Error /\s\+$/
match Error /\t/
match Error /\s\+$/
match Error /\S\zs\s\+$/
match Error / \+\ze\t/

filetype plugin indent on

set wildmenu
set colorcolumn=120

au BufNewFile,BufRead,BufNewFile *.handlebars,*.hbs set ft=html sw=2

highlight Normal ctermbg=NONE
highlight nonText ctermbg=NONE

set exrc

let g:airline_theme = "hybrid"

let g:python_host_prog='/usr/bin/python'
set mouse-=a 
let g:hybrid_use_iTerm_colors = 1
set background=light
colorscheme solarized
let g:solarized_termcolors=256
